version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dispatchgo_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./docs/swagger.yml:/app/swagger.yml:ro
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: dispatchgo_postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d yourdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger:
    image: swaggerapi/swagger-ui:v5.10.3
    container_name: dispatchgo_swagger
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      URL: "/swagger.yml"
    volumes:
      - ./docs/swagger.yml:/usr/share/nginx/html/swagger.yml:ro

volumes:
  db_data: