version: '3.8'
services:
  postgres:
    image: postgres
    container_name: dispatchgo-postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    container_name: dispatchgo-swagger
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /docs/swagger.yml
    volumes:
      - ./docs/swagger.yml:/docs/swagger.yml:ro
    depends_on: []

volumes:
  db_data:
